//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_htc_viu p_htc_viu;
        
        public static SteamVR_Input_ActionSet_htc_viu htc_viu
        {
            get
            {
                return SteamVR_Actions.p_htc_viu.GetCopy<SteamVR_Input_ActionSet_htc_viu>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_htc_viu = ((SteamVR_Input_ActionSet_htc_viu)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_htc_viu>("/actions/htc_viu")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.htc_viu};
        }
    }
}
